wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704181837.856706
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 7
      - 23
      4: 3.10.9
      5: 0.15.4
      6: 4.34.1
      8:
      - 5
    m:
    - 1: train/global_step
      6:
      - 3
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: null
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - RobertaForMaskedLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
    '2': LABEL_2
    '3': LABEL_3
    '4': LABEL_4
    '5': LABEL_5
    '6': LABEL_6
    '7': LABEL_7
    '8': LABEL_8
    '9': LABEL_9
    '10': LABEL_10
    '11': LABEL_11
    '12': LABEL_12
    '13': LABEL_13
    '14': LABEL_14
    '15': LABEL_15
    '16': LABEL_16
    '17': LABEL_17
    '18': LABEL_18
    '19': LABEL_19
    '20': LABEL_20
    '21': LABEL_21
    '22': LABEL_22
    '23': LABEL_23
    '24': LABEL_24
    '25': LABEL_25
    '26': LABEL_26
    '27': LABEL_27
    '28': LABEL_28
    '29': LABEL_29
    '30': LABEL_30
    '31': LABEL_31
    '32': LABEL_32
    '33': LABEL_33
    '34': LABEL_34
    '35': LABEL_35
    '36': LABEL_36
    '37': LABEL_37
    '38': LABEL_38
    '39': LABEL_39
    '40': LABEL_40
    '41': LABEL_41
    '42': LABEL_42
    '43': LABEL_43
    '44': LABEL_44
    '45': LABEL_45
    '46': LABEL_46
    '47': LABEL_47
    '48': LABEL_48
    '49': LABEL_49
    '50': LABEL_50
    '51': LABEL_51
    '52': LABEL_52
    '53': LABEL_53
    '54': LABEL_54
    '55': LABEL_55
    '56': LABEL_56
    '57': LABEL_57
    '58': LABEL_58
    '59': LABEL_59
    '60': LABEL_60
    '61': LABEL_61
    '62': LABEL_62
    '63': LABEL_63
    '64': LABEL_64
    '65': LABEL_65
    '66': LABEL_66
    '67': LABEL_67
    '68': LABEL_68
    '69': LABEL_69
    '70': LABEL_70
    '71': LABEL_71
    '72': LABEL_72
    '73': LABEL_73
    '74': LABEL_74
    '75': LABEL_75
    '76': LABEL_76
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
    LABEL_2: 2
    LABEL_3: 3
    LABEL_4: 4
    LABEL_5: 5
    LABEL_6: 6
    LABEL_7: 7
    LABEL_8: 8
    LABEL_9: 9
    LABEL_10: 10
    LABEL_11: 11
    LABEL_12: 12
    LABEL_13: 13
    LABEL_14: 14
    LABEL_15: 15
    LABEL_16: 16
    LABEL_17: 17
    LABEL_18: 18
    LABEL_19: 19
    LABEL_20: 20
    LABEL_21: 21
    LABEL_22: 22
    LABEL_23: 23
    LABEL_24: 24
    LABEL_25: 25
    LABEL_26: 26
    LABEL_27: 27
    LABEL_28: 28
    LABEL_29: 29
    LABEL_30: 30
    LABEL_31: 31
    LABEL_32: 32
    LABEL_33: 33
    LABEL_34: 34
    LABEL_35: 35
    LABEL_36: 36
    LABEL_37: 37
    LABEL_38: 38
    LABEL_39: 39
    LABEL_40: 40
    LABEL_41: 41
    LABEL_42: 42
    LABEL_43: 43
    LABEL_44: 44
    LABEL_45: 45
    LABEL_46: 46
    LABEL_47: 47
    LABEL_48: 48
    LABEL_49: 49
    LABEL_50: 50
    LABEL_51: 51
    LABEL_52: 52
    LABEL_53: 53
    LABEL_54: 54
    LABEL_55: 55
    LABEL_56: 56
    LABEL_57: 57
    LABEL_58: 58
    LABEL_59: 59
    LABEL_60: 60
    LABEL_61: 61
    LABEL_62: 62
    LABEL_63: 63
    LABEL_64: 64
    LABEL_65: 65
    LABEL_66: 66
    LABEL_67: 67
    LABEL_68: 68
    LABEL_69: 69
    LABEL_70: 70
    LABEL_71: 71
    LABEL_72: 72
    LABEL_73: 73
    LABEL_74: 74
    LABEL_75: 75
    LABEL_76: 76
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 0
pad_token_id:
  desc: null
  value: 1
eos_token_id:
  desc: null
  value: 2
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: roberta-large
transformers_version:
  desc: null
  value: 4.34.1
model_type:
  desc: null
  value: roberta
vocab_size:
  desc: null
  value: 50265
hidden_size:
  desc: null
  value: 1024
num_hidden_layers:
  desc: null
  value: 24
num_attention_heads:
  desc: null
  value: 16
hidden_act:
  desc: null
  value: gelu
intermediate_size:
  desc: null
  value: 4096
hidden_dropout_prob:
  desc: null
  value: 0.1
attention_probs_dropout_prob:
  desc: null
  value: 0.1
max_position_embeddings:
  desc: null
  value: 514
type_vocab_size:
  desc: null
  value: 1
initializer_range:
  desc: null
  value: 0.02
layer_norm_eps:
  desc: null
  value: 1.0e-05
position_embedding_type:
  desc: null
  value: absolute
use_cache:
  desc: null
  value: true
classifier_dropout:
  desc: null
  value: null
output_dir:
  desc: null
  value: ./results
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 16
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: 4000
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./results/runs/Jan02_16-50-52_DICE-57
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: 'no'
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 0.1
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: ./results
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: []
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.1
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
